name: my-front

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # IAM key 세팅 [ repo - settings - secrets - new repository secret ]
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: upload html css js file to S3
        run: |
          aws s3 sync ./templates s3://todaylaw-s3/templates --acl public-read
          aws s3 sync ./static s3://todaylaw-s3/static --acl public-read

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master # 이미 정의된 action을 가져와서 사용
        with:
          args: --acl public-read --exclude '*' --include 'index.html' --include '/static/*' --delete
        env:
           # s3 bucket 이름 세팅 [ repo - settings - secrets - new repository secret ]
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          SOURCE_DIR: 'templates'
          DEST_DIR: 'static'

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          # CloudFront id 세팅
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
          PATHS: 'index.html'
          run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
        continue-on-error: true